CREATE TABLE KHACHHANG(
	MAKH CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40) NOT NULL,
	DCHI VARCHAR(50) NOT NULL,
	SODT VARCHAR(20) NOT NULL,
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY NOT NULL
);
GO

CREATE TABLE NHANVIEN(
	MANV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40) NOT NULL, 
	SODT VARCHAR(20) NOT NULL,
	NGVL SMALLDATETIME NOT NULL,
);
GO

CREATE TABLE SANPHAM(
	MASP CHAR(4) PRIMARY KEY,
	TENSP VARCHAR(40) NOT NULL, 
	DVT VARCHAR(20) NOT NULL,
	NUOCSX VARCHAR(40) NOT NULL,
	GIA MONEY NOT NULL,
);
GO

CREATE TABLE HOADON(
	SOHD INT NOT NULL PRIMARY KEY,
	NGHD SMALLDATETIME NOT NULL, 
	MAKH CHAR(4) FOREIGN KEY REFERENCES KHACHHANG(MAKH)NOT NULL,
	MANV CHAR(4) FOREIGN KEY REFERENCES NHANVIEN(MANV) NOT NULL,
	TRIGIA MONEY NOT NULL,
);
GO

CREATE TABLE CTHD(
	SOHD INT NOT NULL FOREIGN KEY REFERENCES HOADON(SOHD),
	MASP CHAR(4) FOREIGN KEY REFERENCES SANPHAM(MASP),
	SL INT  NOT NULL,
	PRIMARY KEY (SOHD,MASP),
);
GO
------------------
ALTER TABLE SANPHAM
	ADD GHICHU VARCHAR(20);
GO
------------------
ALTER TABLE KHACHHANG
	ADD LOAIKH TINYINT;
GO
-----------------
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);
GO 

 ALTER TABLE SANPHAM
DROP COLUMN GHICHU;
