------------------TÍNH CHU VI DIỆN TÍCH----------------------
DECLARE @DIENTICH FlOAT,
	@CHUVI FLOAT,
	@CHIEUDAI FLOAT=20,
	@CHIEURONG Float=15
	SET @DIENTICH = @CHIEUDAI*@CHIEURONG
	SET @CHUVI= (@CHIEUDAI+@CHIEURONG)*2
	PRINT 'CHU VI BANG:' +CONVERT(CHAR(10),@CHUVI)
	PRINT 'DIEN TICH BANG: '+CONVERT(CHAR(10),@DIENTICH)
GO


------------NHÂN VIÊN CÓ LUONG CAO NHÂT---------------------
DECLARE @MAX_LUONG float
SELECT @MAX_LUONG=MAX(LUONG)
FROM NHANVIEN

SELECT HONV,TENLOT,TENNV,LUONG
FROM NHANVIEN
WHERE LUONG=@MAX_LUONG
GO


------------NHÂN VIÊN CÓ MỨC LƯƠNG TRÊN MỨC TRUNG BÌNH CỦA PHÒNG NGHIÊN CỨU---------------
DECLARE @LUONGTRUGNBINH FLOAT
SELECT @LUONGTRUGNBINH=AVG(LUONG)
FROM NHANVIEN
SELECT HONV+' '+TENLOT+' '+TENNV AS'HỌ VÀ TÊN',LUONG AS'LƯƠNG',TENPHG AS'TÊN PHÒNG'
FROM NHANVIEN,PHONGBAN
WHERE LUONG>@LUONGTRUGNBINH AND TENPHG=N'Nghiên Cứu' AND PHG=5
GO


------------------MỨC LƯƠNG TRUNG BÌNH TRÊN 30000 LIỆT KÊ PHÒNG VÀ SỐ NHÂN VIÊN---------------
DECLARE @LUONGTRUGNBINH FLOAT

SELECT @LUONGTRUGNBINH=AVG(LUONG)
FROM NHANVIEN
SELECT TENPHG AS'TÊN PHÒNG', COUNT(*) AS 'SỐ LƯỢNG NHÂN VIÊN'
FROM NHANVIEN,PHONGBAN
WHERE MAPHG=PHG
GROUP BY TENPHG
HAVING @LUONGTRUGNBINH>30000
GO

--------------------------------------------
DECLARE @SOLUONGDEAN INT
SELECT TENPHG AS'TÊN PHÒNG', COUNT(*)  AS  'SỐ LƯỢNG ĐỀ ÁN ' 
FROM DEAN,PHONGBAN
WHERE PHONG=MAPHG
GROUP BY TENPHG
GO